local DemoScene = require("DemoScene")
local BasicsScene = require("BasicsScene")
local TransitionDemoScene = require("TransitionDemoScene")
local LoopListScene = require("LoopListScene")
local VirtualListScene = require("VirtualListScene")
local HitTestScene = require("HitTestScene")
local PullToRefreshScene = require("PullToRefreshScene")
local ModalWaitingScene = require("ModalWaitingScene")
local JoystickScene = require("JoystickScene")
local BagScene = require("BagScene")
local ChatScene = require("ChatScene")
local ListEffectScene = require("ListEffectScene")
local ScrollPaneScene = require("ScrollPaneScene")
local TreeViewScene = require("TreeViewScene")

local MenuScene = class("MenuScene", DemoScene)

function MenuScene:ctor()
	MenuScene.super.ctor(self)
end

function MenuScene:continueInit()
    fgui.UIPackage:addPackage("UI/MainMenu")
    self._view = fgui.UIPackage:createObject("MainMenu", "Main")
    self._groot:addChild(self._view)

    self._view:getChild("n1"):addClickListener(function (context)
        local scene = cc.TransitionFade:create(0.5, BasicsScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n2"):addClickListener(function (context)
        local scene = cc.TransitionProgressRadialCCW:create(1.0, TransitionDemoScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n4"):addClickListener(function (context)
        local scene = cc.TransitionProgressRadialCCW:create(1, VirtualListScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n5"):addClickListener(function (context)
        local scene = cc.TransitionPageTurn:create(1, LoopListScene:create(), false)
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n6"):addClickListener(function (context)
        local scene = cc.TransitionSlideInL:create(1, HitTestScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n7"):addClickListener(function (context)
        local scene = cc.TransitionSplitRows:create(1, PullToRefreshScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n8"):addClickListener(function (context)
        local scene = cc.TransitionSplitCols:create(1, ModalWaitingScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n9"):addClickListener(function (context)
        local scene = cc.TransitionSplitCols:create(1, JoystickScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n10"):addClickListener(function (context)
        local scene = cc.TransitionSplitCols:create(1, BagScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n11"):addClickListener(function (context)
        local scene = cc.TransitionSplitCols:create(1, ChatScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n12"):addClickListener(function (context)
        local scene = cc.TransitionSplitCols:create(1, ListEffectScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n13"):addClickListener(function (context)
        local scene = cc.TransitionSplitCols:create(1, ScrollPaneScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
    self._view:getChild("n14"):addClickListener(function (context)
        local scene = cc.TransitionSplitCols:create(1, TreeViewScene:create())
        cc.Director:getInstance():replaceScene(scene)
    end)
end


return MenuScene